orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          checkout: true
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
#          context: petland-image-api
          create-repo: true
          dockerfile: Dockerfile
          path: ./
          region: AWS_REGION_ENV_VAR_NAME
          repo: petland-image-api
          tag: '0.0.2'