package com.petland.api.ImagesApi.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "image")
public class Image {

    private String idImage;
    private String name;

    private boolean editable;
    private boolean approval;
    private String s3Url;
    private String requester;
    private boolean approved;
    private String requestDate;
    private List<Field> field;
    private String finalDetails;
    private String category;
    private String openFormat;
    private String closedFormat;
    private String height;
    private String width;


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getIdImage() {
        return idImage;
    }

    public void setIdImage(String idImage) {
        this.idImage = idImage;
    }

    @DynamoDBAttribute
    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    @DynamoDBAttribute
    public String getWidth() {
        return width;
    }

    public void setWidth(String width) {
        this.width = width;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public boolean isEditable() {
        return editable;
    }

    public void setEditable(boolean editable) {
        this.editable = editable;
    }

    @DynamoDBAttribute
    public boolean isApproval() {
        return approval;
    }

    public void setApproval(boolean approval) {
        this.approval = approval;
    }

    @DynamoDBAttribute
    public String getS3Url() {
        return s3Url;
    }

    public void setS3Url(String s3Url) {
        this.s3Url = s3Url;
    }

    @DynamoDBAttribute
    public String getRequester() {
        return requester;
    }

    public void setRequester(String requester) {
        this.requester = requester;
    }

    @DynamoDBAttribute
    public boolean isApproved() {
        return approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }

    @DynamoDBAttribute
    public String getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(String requestDate) {
        this.requestDate = requestDate;
    }

    @DynamoDBAttribute(attributeName = "field")
    public List<Field> getField() {
        return field;
    }

    public void setField(List<Field> field) {
        this.field = field;
    }

    @DynamoDBAttribute
    public String getFinalDetails() {
        return finalDetails;
    }

    public void setFinalDetails(String finalDetails) {
        this.finalDetails = finalDetails;
    }

    @DynamoDBAttribute
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @DynamoDBAttribute
    public String getOpenFormat() {
        return openFormat;
    }

    public void setOpenFormat(String openFormat) {
        this.openFormat = openFormat;
    }

    @DynamoDBAttribute
    public String getClosedFormat() {
        return closedFormat;
    }

    public void setClosedFormat(String closedFormat) {
        this.closedFormat = closedFormat;
    }
}
